version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5431:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    env_file:
      - .env
  django:
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
